#pragma once
// ============================================================================
// prakriti/material/celestial.hpp — Celestial & Planetary Matter Laws
// ============================================================================
// High-performance, header-only material physics for planetary simulation.
// Extends Prakriti with celestial matter presets, inelastic impact heat conversion,
// and Stefan-Boltzmann radiative thermal dissipation.
// ============================================================================

#include "../core/config.hpp"
#include "../state/material_registry.hpp"
#include "../material/phase.hpp"
#include "containers/numeric/math_vector.hpp"

#include <cmath>
#include <algorithm>

namespace prakriti::celestial {

// ── 1. Celestial Material Presets ────────────────────────────────────────────

// 1. Ice / Volatile Crust (Low density, volatile, low melting point)
[[nodiscard]] inline MaterialParams ice_crust() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(920);        // kg/m^3
    p.heat_capacity = Scalar(2.1);       // kJ/(kg*K)
    p.conductivity = Scalar(2.2);        // W/(m*K)
    p.melt_temp = Scalar(0);             // 0 C
    p.boil_temp = Scalar(100);           // 100 C
    p.latent_heat_fusion = Scalar(334);
    p.latent_heat_vapor = Scalar(2257);
    p.yield_strain = Scalar(0.001);
    p.ultimate_strain = Scalar(0.004);   // Brittle
    p.youngs_modulus = Scalar(9e9);
    p.alpha = {Scalar(1e-8), Scalar(1e-5), Scalar(1e-2), Scalar(1)};
    p.visc = {Scalar(0), Scalar(0.05), Scalar(0.01), Scalar(0.001)};
    return p;
}

// 2. Silicate Rock / Planetary Crust & Mantle (Medium density, rocky)
[[nodiscard]] inline MaterialParams silicate_rock() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(2800);       // kg/m^3
    p.heat_capacity = Scalar(0.85);
    p.conductivity = Scalar(2.5);
    p.melt_temp = Scalar(1200);          // 1200 C -> Molten magma
    p.boil_temp = Scalar(2800);          // 2800 C -> Vaporized rock gas
    p.latent_heat_fusion = Scalar(400);
    p.yield_strain = Scalar(0.005);
    p.ultimate_strain = Scalar(0.015);
    p.youngs_modulus = Scalar(7e10);
    p.alpha = {Scalar(1e-9), Scalar(1e-6), Scalar(5e-3), Scalar(1)};
    p.visc = {Scalar(0), Scalar(0.1), Scalar(0.5), Scalar(0.01)};
    return p;
}

// 3. Iron-Nickel Core (High density, metallic, high thermal conductivity)
[[nodiscard]] inline MaterialParams iron_nickel_core() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(7870);       // kg/m^3
    p.heat_capacity = Scalar(0.45);
    p.conductivity = Scalar(50.0);
    p.melt_temp = Scalar(1538);          // 1538 C
    p.boil_temp = Scalar(2862);
    p.latent_heat_fusion = Scalar(270);
    p.yield_strain = Scalar(0.008);
    p.ultimate_strain = Scalar(0.12);    // High ductility before fracture
    p.youngs_modulus = Scalar(2.1e11);
    p.alpha = {Scalar(1e-10), Scalar(1e-7), Scalar(2e-3), Scalar(1)};
    p.visc = {Scalar(0), Scalar(0.2), Scalar(0.1), Scalar(0.005)};
    return p;
}

// 4. Molten Magma / Planetary Lava (Liquid rock state)
[[nodiscard]] inline MaterialParams molten_magma() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(3100);       // kg/m^3
    p.heat_capacity = Scalar(1.2);
    p.conductivity = Scalar(3.0);
    p.melt_temp = Scalar(800);
    p.boil_temp = Scalar(2600);
    p.latent_heat_fusion = Scalar(380);
    p.yield_strain = Scalar(0.02);
    p.ultimate_strain = Scalar(0.1);
    p.youngs_modulus = Scalar(1e8);
    p.alpha = {Scalar(1e-7), Scalar(1e-4), Scalar(5e-2), Scalar(1)};
    p.visc = {Scalar(0), Scalar(0.5), Scalar(2.0), Scalar(0.02)}; // Viscous fluid
    return p;
}

// 5. Superheated Stellar / Core Plasma
[[nodiscard]] inline MaterialParams superheated_plasma() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(1400);       // Compressed plasma gas
    p.heat_capacity = Scalar(4.0);
    p.conductivity = Scalar(100.0);
    p.melt_temp = Scalar(-100);
    p.boil_temp = Scalar(0);
    p.yield_strain = Scalar(0.0);
    p.ultimate_strain = Scalar(0.0);
    p.youngs_modulus = Scalar(0);
    p.alpha = {Scalar(1e-2), Scalar(1e-2), Scalar(1e-1), Scalar(1)};
    p.visc = {Scalar(0.001), Scalar(0.001), Scalar(0.005), Scalar(0.001)};
    return p;
}

// 6. Degenerate Dense Core / Neutron Singularity
[[nodiscard]] inline MaterialParams degenerate_dense_matter() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(50000);      // Extreme gravitational density
    p.heat_capacity = Scalar(0.1);
    p.conductivity = Scalar(1000.0);
    p.melt_temp = Scalar(50000);
    p.boil_temp = Scalar(100000);
    p.yield_strain = Scalar(0.5);
    p.ultimate_strain = Scalar(0.9);
    p.youngs_modulus = Scalar(1e14);
    p.alpha = {Scalar(1e-12), Scalar(1e-10), Scalar(1e-8), Scalar(1e-5)};
    return p;
}

// ── 2. Impact Thermodynamics & Radiative Cooling ─────────────────────────────

// Compute thermal energy generated by inelastic collision between two bodies
// Returns added temperature for body 1 and body 2
struct CollisionHeatResult {
    float temp_delta_1 = 0.0f;
    float temp_delta_2 = 0.0f;
    float total_heat_energy = 0.0f;
};

[[nodiscard]] inline CollisionHeatResult
compute_impact_heat(float m1, float m2, pebble::math::vec2 v1, pebble::math::vec2 v2,
                    float c1, float c2, float restitution = 0.2f) noexcept {
    if (m1 <= 0.0f || m2 <= 0.0f) return {};

    const float total_mass = m1 + m2;
    const float mu = (m1 * m2) / total_mass; // Reduced mass
    const pebble::math::vec2 dv = v1 - v2;
    const float dv2 = dv[0] * dv[0] + dv[1] * dv[1];

    // Inelastic energy loss converted to thermal heat: \Delta Q = 0.5 * (1 - e^2) * mu * dv^2
    const float inelast_factor = std::clamp(1.0f - restitution * restitution, 0.0f, 1.0f);
    const float dQ = 0.5f * inelast_factor * mu * dv2 * 0.05f; // Scaled simulation units

    CollisionHeatResult res;
    res.total_heat_energy = dQ;
    const float c_eff1 = std::max(c1, 0.1f);
    const float c_eff2 = std::max(c2, 0.1f);

    // Heat partitioned proportionally to opposing mass
    res.temp_delta_1 = (dQ * (m2 / total_mass)) / (c_eff1 * m1);
    res.temp_delta_2 = (dQ * (m1 / total_mass)) / (c_eff2 * m2);
    return res;
}

// Stefan-Boltzmann radiative cooling in space: dT/dt = -\epsilon \sigma (T^4 - T_space^4) / (m c)
[[nodiscard]] inline float
apply_radiative_cooling(float current_temp_celsius, float mass, float radius,
                        float dt, float emissivity = 0.85f, float t_space_celsius = -270.0f) noexcept {
    if (mass <= 0.0f || dt <= 0.0f) return current_temp_celsius;

    const float t_k = current_temp_celsius + 273.15f;
    const float t_sp_k = t_space_celsius + 273.15f;
    if (t_k <= t_sp_k) return current_temp_celsius;

    // Simulation radiation cooling rate constant
    constexpr float kRadCoeff = 1.5e-6f;
    const float area = 3.14159265f * radius * radius;
    const float rate = (kRadCoeff * emissivity * area / mass);

    // Smooth temperature decay toward ambient space
    const float dt_k = rate * std::max(t_k - t_sp_k, 0.0f) * dt;
    const float new_t_k = std::max(t_k - dt_k, t_sp_k);
    return new_t_k - 273.15f;
}

// ── 3. Roche Limit & Tidal Disruption ────────────────────────────────────────

// Compute Roche tidal radius: d_tidal = R_heavy * (2 * rho_heavy / rho_light)^(1/3)
[[nodiscard]] inline float
compute_roche_limit(float r_heavy, float rho_heavy, float rho_light, float tidal_rigidity_factor = 2.2f) noexcept {
    if (rho_light <= 0.0f || r_heavy <= 0.0f) return 0.0f;
    const float density_ratio = std::max(0.01f, (2.0f * rho_heavy) / rho_light);
    return r_heavy * std::cbrt(density_ratio) * tidal_rigidity_factor;
}

// ── 4. Contact Binary Dumbbell Coalescence & Collision Regimes ────────────────

enum class CollisionRegime : std::uint8_t {
    ElasticRecoil,        // Momentum rebound & spin torque
    DuctileMerge,         // Contact binary dumbbell accretion
    BrittleFracture,      // Catastrophic fragmentation into shards
    MidMergeDisruption    // Shearing of the connecting neck bridge
};

struct CollisionDecision {
    CollisionRegime regime = CollisionRegime::ElasticRecoil;
    float restitution = 0.35f;
    float friction = 0.25f;
};

// Evaluate collision outcome based on material properties, temperature, ductility, and impact speed
[[nodiscard]] inline CollisionDecision
evaluate_collision_regime(float m1, float m2, float v_rel, float avg_temp,
                          bool is_molten_1, bool is_molten_2,
                          bool is_merging_1, bool is_merging_2) noexcept {
    // Check if violent crash strikes a delicate ongoing contact binary neck
    if ((is_merging_1 || is_merging_2) && v_rel > 25.0f) {
        return {.regime = CollisionRegime::MidMergeDisruption};
    }

    const float mass_ratio = std::max(m1, m2) / std::max(1.0f, std::min(m1, m2));
    const bool is_molten = is_molten_1 || is_molten_2 || (avg_temp > 850.0f);

    // Ductile Accretion: high temperature softening or strong mass capture
    if (is_molten || (mass_ratio > 4.5f && v_rel < 30.0f) || (v_rel < 10.0f && avg_temp > 400.0f)) {
        return {.regime = CollisionRegime::DuctileMerge};
    }

    // Brittle Fracture: cold solid bodies colliding at high impact velocities
    if (!is_molten && v_rel > 38.0f) {
        return {.regime = CollisionRegime::BrittleFracture};
    }

    // Elastic / Inelastic rebound
    const float e = std::clamp(0.45f - (avg_temp / 3000.0f) * 0.35f, 0.08f, 0.65f);
    return {.regime = CollisionRegime::ElasticRecoil, .restitution = e, .friction = 0.25f};
}

// 7. Organic Neutron Star / Pulsar (Super-dense degenerate neutron matter, strong magnetic field)
[[nodiscard]] inline MaterialParams neutron_star() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(2.5e7);       // 2.5 x 10^7 kg/m^3
    p.heat_capacity = Scalar(0.08);
    p.conductivity = Scalar(50000.0);
    p.melt_temp = Scalar(5e6);
    p.boil_temp = Scalar(1e7);
    p.yield_strain = Scalar(0.9);
    p.ultimate_strain = Scalar(0.95);
    p.youngs_modulus = Scalar(1e14);
    p.alpha = {Scalar(1e-12), Scalar(1e-9), Scalar(1e-6), Scalar(1e-3)};
    return p;
}

// 8. Organic Black Hole / Gravitational Singularity (Zero volume, intense relativistic gravity)
[[nodiscard]] inline MaterialParams black_hole_singularity() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(1e9);        // Infinite/Extremely high compact density
    p.heat_capacity = Scalar(0.01);
    p.conductivity = Scalar(10000.0);
    p.melt_temp = Scalar(1e6);
    p.boil_temp = Scalar(1e7);
    p.yield_strain = Scalar(1.0);
    p.ultimate_strain = Scalar(1.0);
    p.youngs_modulus = Scalar(1e18);
    p.alpha = {Scalar(1e-15), Scalar(1e-12), Scalar(1e-9), Scalar(1e-6)};
    return p;
}

// ── 5. Organic Stellar Evolution & Gravitational Collapse (Prakriti Physics Engine) ──────────

enum class StellarPhase : std::uint8_t {
    ColdPlanetoid,       // Asteroids, moons, terrestrial planets
    Protostar,           // Kelvin-Helmholtz gravitational compression heating
    MainSequenceStar,    // Stable Thermonuclear Fusion (Hydrogen/Helium burning)
    SupermassiveGiant,   // Core collapse precursor
    NeutronStar,         // Pulsar / Degenerate Fermi neutron core
    BlackHoleSingularity // Complete gravitational collapse past event horizon
};

struct StellarEvolutionResult {
    StellarPhase phase = StellarPhase::ColdPlanetoid;
    float fusion_heat_rate = 0.0f;       // Thermonuclear energy release (dT/dt)
    float core_compression_rate = 0.0f;  // Gravitational self-compression rate (d\rho/dt)
    bool triggers_supernova = false;
    float event_horizon_radius = 0.0f;
};

// Computes organic stellar evolution, self-gravitational compression, fusion ignition, and collapse thresholds
[[nodiscard]] inline StellarEvolutionResult
evaluate_stellar_evolution(float mass, float density, float current_temp, float radius, float dt) noexcept {
    StellarEvolutionResult res;

    // 1. Black Hole Singularity Regime (TOV limit: M >= 1200, extreme core temperature)
    if (mass >= 1200.0f && (current_temp > 2800.0f || density > 10000.0f)) {
        res.phase = StellarPhase::BlackHoleSingularity;
        res.triggers_supernova = true;
        res.event_horizon_radius = std::clamp(mass * 0.0035f + 2.5f, 2.8f, 10.0f);
        return res;
    }

    // 2. Neutron Star / Pulsar Regime (Chandrasekhar limit: 600 <= M < 1200)
    if (mass >= 600.0f && (current_temp > 2200.0f || density > 6500.0f)) {
        res.phase = StellarPhase::NeutronStar;
        res.triggers_supernova = true;
        res.event_horizon_radius = 2.2f;
        return res;
    }

    // 3. Superheated Main Sequence Fusion Star (M >= 220.0f)
    if (mass >= 220.0f) {
        res.phase = StellarPhase::MainSequenceStar;
        const float fusion_factor = std::clamp((mass - 200.0f) / 600.0f, 0.2f, 1.0f);
        res.fusion_heat_rate = (140.0f + fusion_factor * 260.0f) * dt;
        res.core_compression_rate = 4.0f * dt;
        return res;
    }

    // 4. Protostar Kelvin-Helmholtz Self-Compression (80.0f <= M < 220.0f)
    if (mass >= 80.0f) {
        res.phase = StellarPhase::Protostar;
        const float compression_heat = (mass / 100.0f) * 45.0f * dt;
        res.fusion_heat_rate = compression_heat;
        res.core_compression_rate = 2.0f * dt;
        return res;
    }

    // 5. Standard Cold / Sub-Stellar Body
    res.phase = StellarPhase::ColdPlanetoid;
    return res;
}

// ── 6. Relativistic Gravitational Radiation (Quadrupole Formula & Inspiral Chirp) ────────────

struct GravitationalWaveChirp {
    bool   emits_wave = false;
    float  wave_amplitude = 0.0f;       // Strain amplitude h \propto (G / c^4) * (d^2 Q / dt^2)
    float  energy_loss = 0.0f;          // Radiated energy dE/dt \propto \mu^2 M^{4/3} \omega^{10/3}
    float  chirp_frequency = 0.0f;      // Orbital harmonic frequency
};

// Computes gravitational radiation strain and orbital decay from relativistic inspiral
[[nodiscard]] inline GravitationalWaveChirp
compute_gravitational_wave_emission(float m1, float m2, float dist, float v_rel) noexcept {
    GravitationalWaveChirp chirp;
    const float total_m = m1 + m2;
    if (total_m < 800.0f || dist > 70.0f) return chirp;

    const float mu = (m1 * m2) / total_m; // Reduced mass
    const float d_safe = std::max(dist, 4.0f);
    
    // Relativistic orbital angular velocity: \omega = \sqrt{G M / r^3}
    const float omega = std::sqrt((18000.0f * total_m) / (d_safe * d_safe * d_safe));
    
    // Quadrupole gravitational strain
    const float strain = (mu * omega * omega) / (d_safe * 1500.0f);
    if (strain > 0.02f) {
        chirp.emits_wave = true;
        chirp.wave_amplitude = std::clamp(strain, 0.02f, 1.5f);
        chirp.energy_loss = strain * mu * 0.08f;
        chirp.chirp_frequency = omega * 0.31830988f; // f = \omega / \pi
    }
    return chirp;
}

// ── 7. Cosmic Nucleosynthesis & Elemental Metallicity Index ──────────────────────────────────

struct NucleosynthesisYield {
    float hydrogen_helium = 0.90f; // Primordial light elements
    float silicates_carbon = 0.08f; // Intermediate rocky metallicity
    float iron_peak_metals = 0.02f; // Heavy ferromagnetic cores
};

// Enriches cosmic dust when stars fuse or supernovae detonate
[[nodiscard]] inline NucleosynthesisYield
evaluate_nucleosynthesis(float core_temp, float star_mass, bool is_supernova) noexcept {
    NucleosynthesisYield yield;
    if (is_supernova) {
        // r-process explosive nucleosynthesis: ejects heavy metals & silicates
        yield.hydrogen_helium = 0.20f;
        yield.silicates_carbon = 0.45f;
        yield.iron_peak_metals = 0.35f;
    } else if (core_temp > 2800.0f) {
        // Advanced CNO & Silicon-burning phase
        yield.hydrogen_helium = 0.45f;
        yield.silicates_carbon = 0.40f;
        yield.iron_peak_metals = 0.15f;
    } else if (core_temp > 1200.0f) {
        // Triple-alpha carbon/oxygen fusion
        yield.hydrogen_helium = 0.70f;
        yield.silicates_carbon = 0.26f;
        yield.iron_peak_metals = 0.04f;
    }
    return yield;
}

// ── 8. Innermost Stable Circular Orbit (ISCO) & Relativistic Accretion Flares ────────────────

struct ISCOAccretionResult {
    bool  triggers_flare = false;
    float luminosity_boost = 0.0f;
    float flare_radius = 0.0f;
};

[[nodiscard]] inline ISCOAccretionResult
evaluate_isco_accretion(float body_dist, float bh_mass, float bh_radius) noexcept {
    ISCOAccretionResult res;
    const float isco_radius = bh_radius * 2.8f;
    if (body_dist <= isco_radius) {
        res.triggers_flare = true;
        res.flare_radius = isco_radius;
        res.luminosity_boost = std::clamp((isco_radius - body_dist) / isco_radius, 0.2f, 1.0f);
    }
    return res;
}

// ── 9. Relativistic Ergosphere & Kerr Metric Frame-Dragging ─────────────────────────────────

struct FrameDraggingEffect {
    bool  is_in_ergosphere = false;
    pebble::math::vec2 azimuthal_force{0.0f, 0.0f}; // Lense-Thirring dragging acceleration
    float optical_shear_intensity = 0.0f;
};

// Computes spacetime frame-dragging around spinning Kerr black holes and pulsars
[[nodiscard]] inline FrameDraggingEffect
compute_frame_dragging_swirl(const pebble::math::vec2& p_pos, const pebble::math::vec2& bh_pos,
                             float bh_mass, float bh_radius, float spin_omega) noexcept {
    FrameDraggingEffect eff;
    const pebble::math::vec2 d = p_pos - bh_pos;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);

    // Ergosphere boundary: R_ergo = 2 * R_isco \approx 5.6 * R_bh
    const float ergo_radius = bh_radius * 5.2f;
    if (dist < ergo_radius && dist > 1.0f) {
        eff.is_in_ergosphere = true;
        // Azimuthal tangential vector (perpendicular to radius)
        const pebble::math::vec2 tangent{-d[1] / dist, d[0] / dist};
        
        // Lense-Thirring angular velocity: \omega_{LT} = 2 J / r^3 = (2 * I * spin) / r^3
        const float r_norm = std::max(dist / ergo_radius, 0.08f);
        const float drag_mag = (bh_mass * std::abs(spin_omega)) / (r_norm * r_norm * r_norm * 3200.0f);
        
        const float dir_sign = (spin_omega >= 0.0f) ? 1.0f : -1.0f;
        eff.azimuthal_force = tangent * (drag_mag * dir_sign);
        eff.optical_shear_intensity = std::clamp((ergo_radius - dist) / ergo_radius, 0.1f, 1.0f);
    }
    return eff;
}

// ── 10. Stellar Luminosity & Shadow Eclipse Rays ─────────────────────────────────────────────

struct ShadowCone {
    pebble::math::vec2 apex{0.0f, 0.0f};
    pebble::math::vec2 axis{0.0f, 0.0f};
    float              umbra_angle = 0.0f;
    float              length = 0.0f;
};

[[nodiscard]] inline ShadowCone
compute_stellar_shadow(const pebble::math::vec2& star_pos, const pebble::math::vec2& occluder_pos,
                       float star_radius, float occluder_radius, float max_len = 160.0f) noexcept {
    ShadowCone cone;
    const pebble::math::vec2 dir = occluder_pos - star_pos;
    const float d = std::sqrt(dir[0] * dir[0] + dir[1] * dir[1]);
    if (d < 1.0f) return cone;

    cone.apex = occluder_pos;
    cone.axis = dir * (1.0f / d);
    cone.length = max_len;
    cone.umbra_angle = std::atan2(occluder_radius, d);
    return cone;
}

// ── 11. Quantum Vacuum Matter Condensation & Pair Creation ────────────────────────────────

struct QuantumFluctuationEvent {
    bool  spawns_particle = false;
    float particle_mass = 0.0f;
    float thermal_energy = 0.0f;
};

// Evaluates spontaneous vacuum matter condensation based on cosmic background density and field voids
[[nodiscard]] inline QuantumFluctuationEvent
evaluate_quantum_vacuum_condensation(float local_density_field, float rand_sample) noexcept {
    QuantumFluctuationEvent evt;
    // Lower local matter density increases spontaneous vacuum fluctuation probability (Dirac sea polarization)
    const float vacuum_potential = 1.0f / (1.0f + local_density_field * 0.05f);
    if (rand_sample < vacuum_potential * 0.85f) {
        evt.spawns_particle = true;
        evt.particle_mass = 30.0f + (1.0f - rand_sample) * 45.0f;
        evt.thermal_energy = 25.0f + rand_sample * 80.0f;
    }
    return evt;
}

// ── 12. Kilonova Explosions, r-Process Synthesis & Gamma-Ray Bursts (GRBs) ──────────────────

struct KilonovaResult {
    bool  triggers_kilonova = false;
    float grb_beam_energy = 0.0f;
    float gold_platinum_yield = 0.0f; // Heavy element enrichment delta_Z
    float remnant_mass = 0.0f;
    bool  forms_black_hole = false;
};

[[nodiscard]] inline KilonovaResult
evaluate_kilonova_merger(float m1, float m2, bool is_neutron_1, bool is_neutron_2,
                         bool is_bh_1, bool is_bh_2) noexcept {
    KilonovaResult res;
    // Binary Neutron Star (BNS) or Neutron Star-Black Hole (NSBH) coalescence
    if ((is_neutron_1 && is_neutron_2) || (is_neutron_1 && is_bh_2) || (is_neutron_2 && is_bh_1)) {
        res.triggers_kilonova = true;
        const float total_m = m1 + m2;
        res.remnant_mass = total_m * 0.88f; // ~12% mass converted to pure relativistic energy & ejecta
        res.gold_platinum_yield = std::clamp((m1 * m2) / 45000.0f, 0.02f, 0.08f);
        res.grb_beam_energy = total_m * 12.0f;
        res.forms_black_hole = (total_m > 950.0f); // Exceeds TOV maximum mass for neutron degeneracy
    }
    return res;
}

// ── 13. Planetary & Accretion Ring Formation Dynamics ───────────────────────────────────────

struct RingParticleSpec {
    pebble::math::vec2 pos{0.0f, 0.0f};
    pebble::math::vec2 vel{0.0f, 0.0f};
    float              radius = 0.6f;
    float              mass = 1.0f;
};

// Generates concentric Keplerian ring orbit particles for tidally disrupted moons
[[nodiscard]] inline RingParticleSpec
compute_ring_particle_keplerian(const pebble::math::vec2& host_pos, float host_mass,
                                float ring_radius, float angle, float particle_mass = 1.5f) noexcept {
    RingParticleSpec spec;
    const float cos_a = std::cos(angle);
    const float sin_a = std::sin(angle);
    spec.pos = host_pos + pebble::math::vec2{cos_a, sin_a} * ring_radius;
    
    // Circular Keplerian orbital speed: v = \sqrt{G * M / r}
    const float v_circ = std::sqrt(std::max(1.0f, (18000.0f * host_mass) / std::max(ring_radius, 1.0f)));
    // Tangential orbital velocity vector
    spec.vel = pebble::math::vec2{-sin_a, cos_a} * v_circ;
    spec.mass = particle_mass;
    spec.radius = 0.65f;
    return spec;
}

// ── 14. Gravitational Micro-Lensing Spacetime Deflection ───────────────────────────────────

[[nodiscard]] inline pebble::math::vec2
compute_einstein_micro_lensing(const pebble::math::vec2& ray_pos, const pebble::math::vec2& lens_pos,
                               float lens_mass, float min_impact = 4.0f) noexcept {
    const pebble::math::vec2 d = ray_pos - lens_pos;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);
    if (dist < 1.0f) return pebble::math::vec2{0.0f, 0.0f};

    // General Relativity Deflection Angle: \hat{\alpha} = \frac{4 G M}{c^2 b}
    const float impact_param = std::max(dist, min_impact);
    const float deflection_mag = (lens_mass * 1.8f) / (impact_param * impact_param + 64.0f);
    // Radial deflection towards the gravitating lens
    return pebble::math::vec2{-d[0] / dist, -d[1] / dist} * deflection_mag;
}

// ── 15. Cosmological Metric Expansion (Hubble Drift) ────────────────────────────────────────

[[nodiscard]] inline pebble::math::vec2
apply_hubble_metric_drift(const pebble::math::vec2& pos, const pebble::math::vec2& cosmic_center,
                          float hubble_constant, float dt) noexcept {
    // Hubble's Law: \vec{v}_H = H_0 \cdot \vec{r}
    const pebble::math::vec2 r = pos - cosmic_center;
    return r * (hubble_constant * dt);
}

// ── 16. Supermassive Black Hole (SMBH) Post-Newtonian Inspiral & Ringdown ─────────────────

struct SMBHInspiralState {
    bool  is_in_inspiral = false;
    float gw_chirp_frequency = 0.0f;
    float post_newtonian_drag = 0.0f;
    bool  triggers_ringdown_merger = false;
};

[[nodiscard]] inline SMBHInspiralState
evaluate_smbh_inspiral(float m1, float m2, float distance, float r_isco) noexcept {
    SMBHInspiralState state;
    if (distance < r_isco * 2.5f && distance > 0.5f) {
        state.is_in_inspiral = true;
        // Gravitational Wave Chirp Frequency: \omega \propto (M_chirp)^{5/8} * (r)^{-3/2}
        const float m_chirp = std::pow(m1 * m2, 0.6f) / std::pow(m1 + m2, 0.2f);
        state.gw_chirp_frequency = (std::sqrt(18000.0f * (m1 + m2)) / std::pow(distance, 1.5f)) * 4.0f;
        
        // Post-Newtonian (2.5PN) Radiation Reaction Drag Acceleration
        state.post_newtonian_drag = (m_chirp * 120.0f) / (distance * distance + 16.0f);
        state.triggers_ringdown_merger = (distance <= r_isco * 1.15f);
    }
    return state;
}

// ── 17. Stellar Spaghettification & Tidal Disruption Events (TDE) ───────────────────────────

struct TDESpaghettificationStream {
    bool  is_disrupting = false;
    float tidal_radius = 0.0f;
    float accretion_feed_rate = 0.0f;
};

[[nodiscard]] inline TDESpaghettificationStream
compute_tde_spaghettification(float star_mass, float star_radius, float bh_mass, float distance) noexcept {
    TDESpaghettificationStream stream;
    // Tidal Radius (Hills Radius): r_t = R_* * (M_BH / M_*)^(1/3)
    stream.tidal_radius = star_radius * std::cbrt(std::max(1.0f, bh_mass / std::max(star_mass, 1.0f)));
    if (distance < stream.tidal_radius && distance > 1.0f) {
        stream.is_disrupting = true;
        // Mass transfer rate feeding the ISCO accretion disk
        stream.accretion_feed_rate = std::clamp((stream.tidal_radius - distance) / stream.tidal_radius, 0.1f, 1.0f) * (star_mass * 0.45f);
    }
    return stream;
}

// ── 18. Morgan-Keenan (MK) Stellar Spectral Classification ──────────────────────────────────

enum class SpectralClassMK : std::uint8_t {
    ClassO, // Hyper-luminous Deep Blue Giant (> 30,000 K)
    ClassB, // Blue-White Giant (10,000 - 30,000 K)
    ClassA, // White Sirius (7,500 - 10,000 K)
    ClassF, // Yellow-White Procyon (6,000 - 7,500 K)
    ClassG, // Yellow Sol Sun-like (5,200 - 6,000 K)
    ClassK, // Orange Arcturus (3,700 - 5,200 K)
    ClassM  // Red Dwarf Proxima (< 3,700 K)
};

struct StellarSpectralInfo {
    SpectralClassMK cls = SpectralClassMK::ClassM;
    float r = 1.0f;
    float g = 1.0f;
    float b = 1.0f;
};

[[nodiscard]] inline StellarSpectralInfo
evaluate_stellar_spectral_class(float mass, float temp_celsius) noexcept {
    StellarSpectralInfo info;
    const float t_kelvin = temp_celsius + 273.15f;

    if (t_kelvin >= 28000.0f || mass > 900.0f) {
        info.cls = SpectralClassMK::ClassO;
        info.r = 0.45f; info.g = 0.65f; info.b = 1.0f; // Deep Blue
    } else if (t_kelvin >= 10000.0f || mass > 500.0f) {
        info.cls = SpectralClassMK::ClassB;
        info.r = 0.65f; info.g = 0.82f; info.b = 1.0f; // Blue-White
    } else if (t_kelvin >= 7500.0f || mass > 350.0f) {
        info.cls = SpectralClassMK::ClassA;
        info.r = 0.90f; info.g = 0.95f; info.b = 1.0f; // White
    } else if (t_kelvin >= 6000.0f || mass > 220.0f) {
        info.cls = SpectralClassMK::ClassF;
        info.r = 1.0f;  info.g = 0.98f; info.b = 0.85f; // Yellow-White
    } else if (t_kelvin >= 5200.0f || mass > 140.0f) {
        info.cls = SpectralClassMK::ClassG;
        info.r = 1.0f;  info.g = 0.88f; info.b = 0.35f; // Yellow Sun
    } else if (t_kelvin >= 3700.0f || mass > 80.0f) {
        info.cls = SpectralClassMK::ClassK;
        info.r = 1.0f;  info.g = 0.58f; info.b = 0.20f; // Orange Giant
    } else {
        info.cls = SpectralClassMK::ClassM;
        info.r = 1.0f;  info.g = 0.32f; info.b = 0.15f; // Red Dwarf
    }
    return info;
}

// ── 19. Lin-Shu Galactic Spiral Arm Density Wave Theory ──────────────────────────────────────

[[nodiscard]] inline pebble::math::vec2
compute_lin_shu_spiral_density_wave(const pebble::math::vec2& pos, const pebble::math::vec2& galactic_center,
                                    float galaxy_mass, float pattern_speed = 0.45f, int n_arms = 2) noexcept {
    const pebble::math::vec2 r_vec = pos - galactic_center;
    const float r = std::sqrt(r_vec[0] * r_vec[0] + r_vec[1] * r_vec[1]);
    if (r < 12.0f || r > 500.0f) return pebble::math::vec2{0.0f, 0.0f};

    const float theta = std::atan2(r_vec[1], r_vec[0]);
    // Logarithmic Spiral Arm Phase: \Phi(r, \theta) = n * (\theta - \Omega_p * t) - k * \ln(r / r_0)
    constexpr float pitch_angle_factor = 2.8f;
    const float spiral_phase = static_cast<float>(n_arms) * theta - pitch_angle_factor * std::log(r / 20.0f);

    // Lin-Shu Gravitational Potential Perturbation Force: F_wave = -\nabla \Phi_wave
    const float wave_amp = (galaxy_mass * 0.035f) / (r + 30.0f);
    const float force_azimuthal = -std::sin(spiral_phase) * wave_amp;
    const float force_radial = -std::cos(spiral_phase) * wave_amp * 0.4f;

    const pebble::math::vec2 r_hat = r_vec * (1.0f / r);
    const pebble::math::vec2 theta_hat{-r_hat[1], r_hat[0]};

    return r_hat * force_radial + theta_hat * force_azimuthal;
}

// ── 20. Stellar Wind & Coronal Mass Ejection (CME) Radiation Pressure ───────────────────────

struct StellarWindForce {
    pebble::math::vec2 force{0.0f, 0.0f};
    bool               triggers_cme = false;
};

[[nodiscard]] inline StellarWindForce
evaluate_stellar_wind_radiation_pressure(const pebble::math::vec2& star_pos, float star_mass,
                                         float star_temp, float star_radius,
                                         const pebble::math::vec2& target_pos, float rand_sample) noexcept {
    StellarWindForce res;
    if (star_temp < 1400.0f && star_mass < 120.0f) return res;

    const pebble::math::vec2 d = target_pos - star_pos;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);
    if (dist < star_radius || dist > 260.0f) return res;

    // Stefan-Boltzmann Luminosity: L \propto R^2 * T^4
    const float t_norm = star_temp / 5500.0f;
    const float luminosity = (star_radius * star_radius) * (t_norm * t_norm * t_norm * t_norm);
    
    // Radiation Pressure: F_rad = \frac{L}{4\pi r^2 c}
    const float rad_press = (luminosity * 140.0f) / (dist_sq + 100.0f);
    res.force = pebble::math::vec2{d[0] / dist, d[1] / dist} * rad_press;

    // Periodic Coronal Mass Ejection (CME) Magnetic Flare Eruptions
    if (star_temp > 2200.0f && rand_sample < 0.004f) {
        res.triggers_cme = true;
    }
    return res;
}

// ── 21. Barycentric Hierarchy Detection (Jacobi Coordinates) ───────────────────────────────

struct BarycentricPair {
    std::size_t        idx1 = 0;
    std::size_t        idx2 = 0;
    pebble::math::vec2 center_of_mass{0.0f, 0.0f};
    float              total_mass = 0.0f;
    float              separation = 0.0f;
    bool               is_bound = false;
};

[[nodiscard]] inline BarycentricPair
detect_binary_barycenter(std::size_t i, std::size_t j,
                         const pebble::math::vec2& p1, const pebble::math::vec2& v1, float m1,
                         const pebble::math::vec2& p2, const pebble::math::vec2& v2, float m2) noexcept {
    BarycentricPair pair;
    pair.idx1 = i;
    pair.idx2 = j;
    const pebble::math::vec2 d = p2 - p1;
    pair.separation = std::sqrt(d[0] * d[0] + d[1] * d[1]);
    pair.total_mass = m1 + m2;
    pair.center_of_mass = (p1 * m1 + p2 * m2) * (1.0f / pair.total_mass);

    // Mutual Orbital Specific Energy: \epsilon = \frac{1}{2} v_{rel}^2 - \frac{G M_{tot}}{r}
    const pebble::math::vec2 dv = v2 - v1;
    const float v_rel_sq = dv[0] * dv[0] + dv[1] * dv[1];
    const float spec_energy = 0.5f * v_rel_sq - (18000.0f * pair.total_mass) / (pair.separation + 10.0f);

    pair.is_bound = (spec_energy < 0.0f && pair.separation < 220.0f);
    return pair;
}

// ── 22. Cosmic Filament Web (Zel'dovich Approximation) ──────────────────────────────────────

struct CosmicFilamentBridge {
    pebble::math::vec2 node_a{0.0f, 0.0f};
    pebble::math::vec2 node_b{0.0f, 0.0f};
    float              filament_density = 0.0f;
};

[[nodiscard]] inline CosmicFilamentBridge
compute_cosmic_filament(const pebble::math::vec2& p1, float m1,
                        const pebble::math::vec2& p2, float m2, float max_span = 450.0f) noexcept {
    CosmicFilamentBridge f;
    f.node_a = p1;
    f.node_b = p2;
    const pebble::math::vec2 d = p2 - p1;
    const float len = std::sqrt(d[0] * d[0] + d[1] * d[1]);
    if (len > 30.0f && len < max_span) {
        // Gravitational bridge density between supermassive nodes
        f.filament_density = std::clamp((m1 * m2) / (len * len * 8.0f), 0.05f, 0.65f);
    }
    return f;
}

// ── 23. Spacetime Curvature & Geodesic Grid Embedding ──────────────────────────────────────

[[nodiscard]] inline pebble::math::vec2
compute_spacetime_geodesic_deflection(const pebble::math::vec2& grid_pt,
                                      const pebble::math::vec2& mass_pos,
                                      float mass, float softening = 24.0f) noexcept {
    const pebble::math::vec2 d = mass_pos - grid_pt;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);
    if (dist < 1.0f) return pebble::math::vec2{0.0f, 0.0f};

    // 2D Spacetime Curvature Warping: \Delta \vec{x} = \frac{G M}{r^2 + \epsilon^2} \hat{r}
    const float pinch_mag = (mass * 0.45f) / (dist_sq + softening * softening);
    return pebble::math::vec2{d[0] / dist, d[1] / dist} * std::min(pinch_mag, 16.0f);
}

// ── 24. Hawking Radiation Quantum Black Hole Evaporation ───────────────────────────────────

struct HawkingRadiationState {
    float mass_loss_rate = 0.0f;
    float hawking_temp = 0.0f;
    bool  triggers_gamma_flash = false;
};

[[nodiscard]] inline HawkingRadiationState
evaluate_hawking_radiation(float mass, float dt) noexcept {
    HawkingRadiationState res;
    if (mass < 1.0f) return res;

    // Hawking Temperature: T_H \propto 1 / M
    res.hawking_temp = 12000.0f / (mass * 0.05f + 1.0f);

    // Mass Loss Rate: dM/dt \propto -1 / M^2
    res.mass_loss_rate = (14.0f / (mass * mass * 0.001f + 1.0f)) * dt;

    // High-Energy Gamma-Ray Flash when below critical degenerate mass
    res.triggers_gamma_flash = (mass <= 45.0f);
    return res;
}

// ── 25. General Relativistic Gravitational Redshift ─────────────────────────────────────────

[[nodiscard]] inline float
compute_gravitational_redshift_factor(float mass, float radius, float distance) noexcept {
    // Gravitational Redshift Factor: z = \frac{1}{\sqrt{1 - \frac{2 G M}{c^2 r}}} - 1
    const float r_eff = std::max(radius, distance);
    const float rs = (mass * 0.0035f + 2.5f); // Effective Schwarzschild radius
    const float schw_ratio = std::clamp(rs / (r_eff + 1.0f), 0.0f, 0.88f);
    return (1.0f / std::sqrt(1.0f - schw_ratio)) - 1.0f;
}

// ── 26. Forward Keplerian / Osculating Orbit Prediction ──────────────────────────────────────

struct OrbitPredictionPoint {
    pebble::math::vec2 pos{0.0f, 0.0f};
    bool               is_bound = false;
};

[[nodiscard]] inline std::vector<pebble::math::vec2>
compute_osculating_orbit_points(const pebble::math::vec2& body_pos, const pebble::math::vec2& body_vel,
                                const pebble::math::vec2& host_pos, float host_mass,
                                int num_steps = 28, float dt_step = 0.08f) noexcept {
    std::vector<pebble::math::vec2> points;
    points.reserve(num_steps);

    pebble::math::vec2 sim_p = body_pos;
    pebble::math::vec2 sim_v = body_vel;

    for (int step = 0; step < num_steps; ++step) {
        const pebble::math::vec2 d = host_pos - sim_p;
        const float dist2 = d[0] * d[0] + d[1] * d[1] + 16.0f;
        const float dist = std::sqrt(dist2);
        const pebble::math::vec2 a = pebble::math::vec2{d[0] / dist, d[1] / dist} * ((18000.0f * host_mass) / dist2);

        sim_v = sim_v + a * dt_step;
        sim_p = sim_p + sim_v * dt_step;
        points.push_back(sim_p);
    }
    return points;
}

// ── 27. Cosmic Ray Synchrotron Magnetic Shockwave Arcs ───────────────────────────────────────

struct SynchrotronArc {
    pebble::math::vec2 center{0.0f, 0.0f};
    float              radius = 0.0f;
    float              start_angle = 0.0f;
    float              end_angle = 0.0f;
    float              intensity = 1.0f;
};

[[nodiscard]] inline SynchrotronArc
compute_synchrotron_shock_arc(const pebble::math::vec2& origin, const pebble::math::vec2& dir,
                              float shock_radius, float energy_density) noexcept {
    SynchrotronArc arc;
    arc.center = origin;
    arc.radius = shock_radius;
    const float base_angle = std::atan2(dir[1], dir[0]);
    arc.start_angle = base_angle - 0.75f;
    arc.end_angle = base_angle + 0.75f;
    arc.intensity = std::clamp(energy_density * 0.02f, 0.2f, 0.95f);
    return arc;
}

} // namespace prakriti::celestial
