#pragma once
// ============================================================================
// prakriti/material/celestial.hpp — Celestial & Planetary Matter Laws
// ============================================================================
// High-performance, header-only material physics for planetary simulation.
// Extends Prakriti with celestial matter presets, inelastic impact heat conversion,
// and Stefan-Boltzmann radiative thermal dissipation.
// ============================================================================

#include "../core/config.hpp"
#include "../state/material_registry.hpp"
#include "../material/phase.hpp"
#include "containers/numeric/math_vector.hpp"

#include <cmath>
#include <algorithm>

namespace prakriti::celestial {

// ── 1. Celestial Material Presets ────────────────────────────────────────────

// 1. Ice / Volatile Crust (Low density, volatile, low melting point)
[[nodiscard]] inline MaterialParams ice_crust() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(920);        // kg/m^3
    p.heat_capacity = Scalar(2.1);       // kJ/(kg*K)
    p.conductivity = Scalar(2.2);        // W/(m*K)
    p.melt_temp = Scalar(0);             // 0 C
    p.boil_temp = Scalar(100);           // 100 C
    p.latent_heat_fusion = Scalar(334);
    p.latent_heat_vapor = Scalar(2257);
    p.yield_strain = Scalar(0.001);
    p.ultimate_strain = Scalar(0.004);   // Brittle
    p.youngs_modulus = Scalar(9e9);
    p.alpha = {Scalar(1e-8), Scalar(1e-5), Scalar(1e-2), Scalar(1)};
    p.visc = {Scalar(0), Scalar(0.05), Scalar(0.01), Scalar(0.001)};
    return p;
}

// 2. Silicate Rock / Planetary Crust & Mantle (Medium density, rocky)
[[nodiscard]] inline MaterialParams silicate_rock() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(2800);       // kg/m^3
    p.heat_capacity = Scalar(0.85);
    p.conductivity = Scalar(2.5);
    p.melt_temp = Scalar(1200);          // 1200 C -> Molten magma
    p.boil_temp = Scalar(2800);          // 2800 C -> Vaporized rock gas
    p.latent_heat_fusion = Scalar(400);
    p.yield_strain = Scalar(0.005);
    p.ultimate_strain = Scalar(0.015);
    p.youngs_modulus = Scalar(7e10);
    p.alpha = {Scalar(1e-9), Scalar(1e-6), Scalar(5e-3), Scalar(1)};
    p.visc = {Scalar(0), Scalar(0.1), Scalar(0.5), Scalar(0.01)};
    return p;
}

// 3. Iron-Nickel Core (High density, metallic, high thermal conductivity)
[[nodiscard]] inline MaterialParams iron_nickel_core() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(7870);       // kg/m^3
    p.heat_capacity = Scalar(0.45);
    p.conductivity = Scalar(50.0);
    p.melt_temp = Scalar(1538);          // 1538 C
    p.boil_temp = Scalar(2862);
    p.latent_heat_fusion = Scalar(270);
    p.yield_strain = Scalar(0.008);
    p.ultimate_strain = Scalar(0.12);    // High ductility before fracture
    p.youngs_modulus = Scalar(2.1e11);
    p.alpha = {Scalar(1e-10), Scalar(1e-7), Scalar(2e-3), Scalar(1)};
    p.visc = {Scalar(0), Scalar(0.2), Scalar(0.1), Scalar(0.005)};
    return p;
}

// 4. Molten Magma / Planetary Lava (Liquid rock state)
[[nodiscard]] inline MaterialParams molten_magma() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(3100);       // kg/m^3
    p.heat_capacity = Scalar(1.2);
    p.conductivity = Scalar(3.0);
    p.melt_temp = Scalar(800);
    p.boil_temp = Scalar(2600);
    p.latent_heat_fusion = Scalar(380);
    p.yield_strain = Scalar(0.02);
    p.ultimate_strain = Scalar(0.1);
    p.youngs_modulus = Scalar(1e8);
    p.alpha = {Scalar(1e-7), Scalar(1e-4), Scalar(5e-2), Scalar(1)};
    p.visc = {Scalar(0), Scalar(0.5), Scalar(2.0), Scalar(0.02)}; // Viscous fluid
    return p;
}

// 5. Superheated Stellar / Core Plasma
[[nodiscard]] inline MaterialParams superheated_plasma() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(1400);       // Compressed plasma gas
    p.heat_capacity = Scalar(4.0);
    p.conductivity = Scalar(100.0);
    p.melt_temp = Scalar(-100);
    p.boil_temp = Scalar(0);
    p.yield_strain = Scalar(0.0);
    p.ultimate_strain = Scalar(0.0);
    p.youngs_modulus = Scalar(0);
    p.alpha = {Scalar(1e-2), Scalar(1e-2), Scalar(1e-1), Scalar(1)};
    p.visc = {Scalar(0.001), Scalar(0.001), Scalar(0.005), Scalar(0.001)};
    return p;
}

// 6. Degenerate Dense Core / Neutron Singularity
[[nodiscard]] inline MaterialParams degenerate_dense_matter() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(50000);      // Extreme gravitational density
    p.heat_capacity = Scalar(0.1);
    p.conductivity = Scalar(1000.0);
    p.melt_temp = Scalar(50000);
    p.boil_temp = Scalar(100000);
    p.yield_strain = Scalar(0.5);
    p.ultimate_strain = Scalar(0.9);
    p.youngs_modulus = Scalar(1e14);
    p.alpha = {Scalar(1e-12), Scalar(1e-10), Scalar(1e-8), Scalar(1e-5)};
    return p;
}

// ── 2. Impact Thermodynamics & Radiative Cooling ─────────────────────────────

// Compute thermal energy generated by inelastic collision between two bodies
// Returns added temperature for body 1 and body 2
struct CollisionHeatResult {
    float temp_delta_1 = 0.0f;
    float temp_delta_2 = 0.0f;
    float total_heat_energy = 0.0f;
};

[[nodiscard]] inline CollisionHeatResult
compute_impact_heat(float m1, float m2, pebble::math::vec2 v1, pebble::math::vec2 v2,
                    float c1, float c2, float restitution = 0.2f) noexcept {
    if (m1 <= 0.0f || m2 <= 0.0f) return {};

    const float total_mass = m1 + m2;
    const float mu = (m1 * m2) / total_mass; // Reduced mass
    const pebble::math::vec2 dv = v1 - v2;
    const float dv2 = dv[0] * dv[0] + dv[1] * dv[1];

    // Inelastic energy loss converted to thermal heat: \Delta Q = 0.5 * (1 - e^2) * mu * dv^2
    const float inelast_factor = std::clamp(1.0f - restitution * restitution, 0.0f, 1.0f);
    const float dQ = 0.5f * inelast_factor * mu * dv2 * 0.05f; // Scaled simulation units

    CollisionHeatResult res;
    res.total_heat_energy = dQ;
    const float c_eff1 = std::max(c1, 0.1f);
    const float c_eff2 = std::max(c2, 0.1f);

    // Heat partitioned proportionally to opposing mass
    res.temp_delta_1 = (dQ * (m2 / total_mass)) / (c_eff1 * m1);
    res.temp_delta_2 = (dQ * (m1 / total_mass)) / (c_eff2 * m2);
    return res;
}

// Stefan-Boltzmann radiative cooling in space: dT/dt = -\epsilon \sigma (T^4 - T_space^4) / (m c)
[[nodiscard]] inline float
apply_radiative_cooling(float current_temp_celsius, float mass, float radius,
                        float dt, float emissivity = 0.85f, float t_space_celsius = -270.0f) noexcept {
    if (mass <= 0.0f || dt <= 0.0f) return current_temp_celsius;

    const float t_k = current_temp_celsius + 273.15f;
    const float t_sp_k = t_space_celsius + 273.15f;
    if (t_k <= t_sp_k) return current_temp_celsius;

    // Simulation radiation cooling rate constant
    constexpr float kRadCoeff = 1.5e-6f;
    const float area = 3.14159265f * radius * radius;
    const float rate = (kRadCoeff * emissivity * area / mass);

    // Smooth temperature decay toward ambient space
    const float dt_k = rate * std::max(t_k - t_sp_k, 0.0f) * dt;
    const float new_t_k = std::max(t_k - dt_k, t_sp_k);
    return new_t_k - 273.15f;
}

// ── 3. Roche Limit & Tidal Disruption ────────────────────────────────────────

// Compute Roche tidal radius: d_tidal = R_heavy * (2 * rho_heavy / rho_light)^(1/3)
[[nodiscard]] inline float
compute_roche_limit(float r_heavy, float rho_heavy, float rho_light, float tidal_rigidity_factor = 2.2f) noexcept {
    if (rho_light <= 0.0f || r_heavy <= 0.0f) return 0.0f;
    const float density_ratio = std::max(0.01f, (2.0f * rho_heavy) / rho_light);
    return r_heavy * std::cbrt(density_ratio) * tidal_rigidity_factor;
}

// ── 4. Contact Binary Dumbbell Coalescence & Collision Regimes ────────────────

enum class CollisionRegime : std::uint8_t {
    ElasticRecoil,        // Momentum rebound & spin torque
    DuctileMerge,         // Contact binary dumbbell accretion
    BrittleFracture,      // Catastrophic fragmentation into shards
    MidMergeDisruption    // Shearing of the connecting neck bridge
};

struct CollisionDecision {
    CollisionRegime regime = CollisionRegime::ElasticRecoil;
    float restitution = 0.35f;
    float friction = 0.25f;
};

// Evaluate collision outcome based on material properties, temperature, ductility, and impact speed
[[nodiscard]] inline CollisionDecision
evaluate_collision_regime(float m1, float m2, float v_rel, float avg_temp,
                          bool is_molten_1, bool is_molten_2,
                          bool is_merging_1, bool is_merging_2) noexcept {
    // Check if violent crash strikes a delicate ongoing contact binary neck
    if ((is_merging_1 || is_merging_2) && v_rel > 25.0f) {
        return {.regime = CollisionRegime::MidMergeDisruption};
    }

    const float mass_ratio = std::max(m1, m2) / std::max(1.0f, std::min(m1, m2));
    const bool is_molten = is_molten_1 || is_molten_2 || (avg_temp > 850.0f);

    // Ductile Accretion: high temperature softening or strong mass capture
    if (is_molten || (mass_ratio > 4.5f && v_rel < 30.0f) || (v_rel < 10.0f && avg_temp > 400.0f)) {
        return {.regime = CollisionRegime::DuctileMerge};
    }

    // Brittle Fracture: cold solid bodies colliding at high impact velocities
    if (!is_molten && v_rel > 38.0f) {
        return {.regime = CollisionRegime::BrittleFracture};
    }

    // Elastic / Inelastic rebound
    const float e = std::clamp(0.45f - (avg_temp / 3000.0f) * 0.35f, 0.08f, 0.65f);
    return {.regime = CollisionRegime::ElasticRecoil, .restitution = e, .friction = 0.25f};
}

// 7. Organic Neutron Star / Pulsar (Super-dense degenerate neutron matter, strong magnetic field)
[[nodiscard]] inline MaterialParams neutron_star() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(2.5e7);       // 2.5 x 10^7 kg/m^3
    p.heat_capacity = Scalar(0.08);
    p.conductivity = Scalar(50000.0);
    p.melt_temp = Scalar(5e6);
    p.boil_temp = Scalar(1e7);
    p.yield_strain = Scalar(0.9);
    p.ultimate_strain = Scalar(0.95);
    p.youngs_modulus = Scalar(1e14);
    p.alpha = {Scalar(1e-12), Scalar(1e-9), Scalar(1e-6), Scalar(1e-3)};
    return p;
}

// 8. Organic Black Hole / Gravitational Singularity (Zero volume, intense relativistic gravity)
[[nodiscard]] inline MaterialParams black_hole_singularity() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(1e9);        // Infinite/Extremely high compact density
    p.heat_capacity = Scalar(0.01);
    p.conductivity = Scalar(10000.0);
    p.melt_temp = Scalar(1e6);
    p.boil_temp = Scalar(1e7);
    p.yield_strain = Scalar(1.0);
    p.ultimate_strain = Scalar(1.0);
    p.youngs_modulus = Scalar(1e18);
    p.alpha = {Scalar(1e-15), Scalar(1e-12), Scalar(1e-9), Scalar(1e-6)};
    return p;
}

// 9. Strange Quark Star (Deconfined u,d,s quark matter, intermediate between neutron star and black hole)
[[nodiscard]] inline MaterialParams strange_quark_star() noexcept {
    MaterialParams p;
    p.rest_density = Scalar(4.2e7);       // 4.2 x 10^7 kg/m^3
    p.heat_capacity = Scalar(0.05);
    p.conductivity = Scalar(100000.0);
    p.melt_temp = Scalar(1e7);
    p.boil_temp = Scalar(5e7);
    p.yield_strain = Scalar(0.98);
    p.ultimate_strain = Scalar(0.99);
    p.youngs_modulus = Scalar(1e16);
    p.alpha = {Scalar(1e-14), Scalar(1e-11), Scalar(1e-8), Scalar(1e-5)};
    return p;
}

// ── 5. Organic Stellar Evolution & Gravitational Collapse (Prakriti Physics Engine) ──────────

enum class StellarPhase : std::uint8_t {
    ColdPlanetoid,       // Asteroids, moons, terrestrial planets
    Protostar,           // Kelvin-Helmholtz gravitational compression heating
    MainSequenceStar,    // Stable Thermonuclear Fusion (Hydrogen/Helium burning)
    SupermassiveGiant,   // Core collapse precursor
    NeutronStar,         // Pulsar / Degenerate Fermi neutron core
    BlackHoleSingularity // Complete gravitational collapse past event horizon
};

struct StellarEvolutionResult {
    StellarPhase phase = StellarPhase::ColdPlanetoid;
    float fusion_heat_rate = 0.0f;       // Thermonuclear energy release (dT/dt)
    float core_compression_rate = 0.0f;  // Gravitational self-compression rate (d\rho/dt)
    bool triggers_supernova = false;
    float event_horizon_radius = 0.0f;
};

// Computes organic stellar evolution, self-gravitational compression, fusion ignition, and collapse thresholds
[[nodiscard]] inline StellarEvolutionResult
evaluate_stellar_evolution(float mass, float density, float current_temp, float radius, float dt) noexcept {
    StellarEvolutionResult res;

    // 1. Black Hole Singularity Regime (TOV limit: M >= 1200, extreme core temperature)
    if (mass >= 1200.0f && (current_temp > 2800.0f || density > 10000.0f)) {
        res.phase = StellarPhase::BlackHoleSingularity;
        res.triggers_supernova = true;
        res.event_horizon_radius = std::clamp(mass * 0.0035f + 2.5f, 2.8f, 10.0f);
        return res;
    }

    // 2. Neutron Star / Pulsar Regime (Chandrasekhar limit: 600 <= M < 1200)
    if (mass >= 600.0f && (current_temp > 2200.0f || density > 6500.0f)) {
        res.phase = StellarPhase::NeutronStar;
        res.triggers_supernova = true;
        res.event_horizon_radius = 2.2f;
        return res;
    }

    // 3. Superheated Main Sequence Fusion Star (M >= 220.0f)
    if (mass >= 220.0f) {
        res.phase = StellarPhase::MainSequenceStar;
        const float fusion_factor = std::clamp((mass - 200.0f) / 600.0f, 0.2f, 1.0f);
        res.fusion_heat_rate = (140.0f + fusion_factor * 260.0f) * dt;
        res.core_compression_rate = 4.0f * dt;
        return res;
    }

    // 4. Protostar Kelvin-Helmholtz Self-Compression (80.0f <= M < 220.0f)
    if (mass >= 80.0f) {
        res.phase = StellarPhase::Protostar;
        const float compression_heat = (mass / 100.0f) * 45.0f * dt;
        res.fusion_heat_rate = compression_heat;
        res.core_compression_rate = 2.0f * dt;
        return res;
    }

    // 5. Standard Cold / Sub-Stellar Body
    res.phase = StellarPhase::ColdPlanetoid;
    return res;
}

// ── 6. Relativistic Gravitational Radiation (Quadrupole Formula & Inspiral Chirp) ────────────

struct GravitationalWaveChirp {
    bool   emits_wave = false;
    float  wave_amplitude = 0.0f;       // Strain amplitude h \propto (G / c^4) * (d^2 Q / dt^2)
    float  energy_loss = 0.0f;          // Radiated energy dE/dt \propto \mu^2 M^{4/3} \omega^{10/3}
    float  chirp_frequency = 0.0f;      // Orbital harmonic frequency
};

// Computes gravitational radiation strain and orbital decay from relativistic inspiral
[[nodiscard]] inline GravitationalWaveChirp
compute_gravitational_wave_emission(float m1, float m2, float dist, float v_rel) noexcept {
    GravitationalWaveChirp chirp;
    const float total_m = m1 + m2;
    if (total_m < 800.0f || dist > 70.0f) return chirp;

    const float mu = (m1 * m2) / total_m; // Reduced mass
    const float d_safe = std::max(dist, 4.0f);
    
    // Relativistic orbital angular velocity: \omega = \sqrt{G M / r^3}
    const float omega = std::sqrt((18000.0f * total_m) / (d_safe * d_safe * d_safe));
    
    // Quadrupole gravitational strain
    const float strain = (mu * omega * omega) / (d_safe * 1500.0f);
    if (strain > 0.02f) {
        chirp.emits_wave = true;
        chirp.wave_amplitude = std::clamp(strain, 0.02f, 1.5f);
        chirp.energy_loss = strain * mu * 0.08f;
        chirp.chirp_frequency = omega * 0.31830988f; // f = \omega / \pi
    }
    return chirp;
}

// ── 7. Cosmic Nucleosynthesis & Elemental Metallicity Index ──────────────────────────────────

struct NucleosynthesisYield {
    float hydrogen_helium = 0.90f; // Primordial light elements
    float silicates_carbon = 0.08f; // Intermediate rocky metallicity
    float iron_peak_metals = 0.02f; // Heavy ferromagnetic cores
};

// Enriches cosmic dust when stars fuse or supernovae detonate
[[nodiscard]] inline NucleosynthesisYield
evaluate_nucleosynthesis(float core_temp, float star_mass, bool is_supernova) noexcept {
    NucleosynthesisYield yield;
    if (is_supernova) {
        // r-process explosive nucleosynthesis: ejects heavy metals & silicates
        yield.hydrogen_helium = 0.20f;
        yield.silicates_carbon = 0.45f;
        yield.iron_peak_metals = 0.35f;
    } else if (core_temp > 2800.0f) {
        // Advanced CNO & Silicon-burning phase
        yield.hydrogen_helium = 0.45f;
        yield.silicates_carbon = 0.40f;
        yield.iron_peak_metals = 0.15f;
    } else if (core_temp > 1200.0f) {
        // Triple-alpha carbon/oxygen fusion
        yield.hydrogen_helium = 0.70f;
        yield.silicates_carbon = 0.26f;
        yield.iron_peak_metals = 0.04f;
    }
    return yield;
}

// ── 8. Innermost Stable Circular Orbit (ISCO) & Relativistic Accretion Flares ────────────────

struct ISCOAccretionResult {
    bool  triggers_flare = false;
    float luminosity_boost = 0.0f;
    float flare_radius = 0.0f;
};

[[nodiscard]] inline ISCOAccretionResult
evaluate_isco_accretion(float body_dist, float bh_mass, float bh_radius) noexcept {
    ISCOAccretionResult res;
    const float isco_radius = bh_radius * 2.8f;
    if (body_dist <= isco_radius) {
        res.triggers_flare = true;
        res.flare_radius = isco_radius;
        res.luminosity_boost = std::clamp((isco_radius - body_dist) / isco_radius, 0.2f, 1.0f);
    }
    return res;
}

// ── 9. Relativistic Ergosphere & Kerr Metric Frame-Dragging ─────────────────────────────────

struct FrameDraggingEffect {
    bool  is_in_ergosphere = false;
    pebble::math::vec2 azimuthal_force{0.0f, 0.0f}; // Lense-Thirring dragging acceleration
    float optical_shear_intensity = 0.0f;
};

// Computes spacetime frame-dragging around spinning Kerr black holes and pulsars
[[nodiscard]] inline FrameDraggingEffect
compute_frame_dragging_swirl(const pebble::math::vec2& p_pos, const pebble::math::vec2& bh_pos,
                             float bh_mass, float bh_radius, float spin_omega) noexcept {
    FrameDraggingEffect eff;
    const pebble::math::vec2 d = p_pos - bh_pos;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);

    // Ergosphere boundary: R_ergo = 2 * R_isco \approx 5.6 * R_bh
    const float ergo_radius = bh_radius * 5.2f;
    if (dist < ergo_radius && dist > 1.0f) {
        eff.is_in_ergosphere = true;
        // Azimuthal tangential vector (perpendicular to radius)
        const pebble::math::vec2 tangent{-d[1] / dist, d[0] / dist};
        
        // Lense-Thirring angular velocity: \omega_{LT} = 2 J / r^3 = (2 * I * spin) / r^3
        const float r_norm = std::max(dist / ergo_radius, 0.08f);
        const float drag_mag = (bh_mass * std::abs(spin_omega)) / (r_norm * r_norm * r_norm * 3200.0f);
        
        const float dir_sign = (spin_omega >= 0.0f) ? 1.0f : -1.0f;
        eff.azimuthal_force = tangent * (drag_mag * dir_sign);
        eff.optical_shear_intensity = std::clamp((ergo_radius - dist) / ergo_radius, 0.1f, 1.0f);
    }
    return eff;
}

// ── 10. Stellar Luminosity & Shadow Eclipse Rays ─────────────────────────────────────────────

struct ShadowCone {
    pebble::math::vec2 apex{0.0f, 0.0f};
    pebble::math::vec2 axis{0.0f, 0.0f};
    float              umbra_angle = 0.0f;
    float              length = 0.0f;
};

[[nodiscard]] inline ShadowCone
compute_stellar_shadow(const pebble::math::vec2& star_pos, const pebble::math::vec2& occluder_pos,
                       float star_radius, float occluder_radius, float max_len = 160.0f) noexcept {
    ShadowCone cone;
    const pebble::math::vec2 dir = occluder_pos - star_pos;
    const float d = std::sqrt(dir[0] * dir[0] + dir[1] * dir[1]);
    if (d < 1.0f) return cone;

    cone.apex = occluder_pos;
    cone.axis = dir * (1.0f / d);
    cone.length = max_len;
    cone.umbra_angle = std::atan2(occluder_radius, d);
    return cone;
}

// ── 11. Quantum Vacuum Matter Condensation & Pair Creation ────────────────────────────────

struct QuantumFluctuationEvent {
    bool  spawns_particle = false;
    float particle_mass = 0.0f;
    float thermal_energy = 0.0f;
};

// Evaluates spontaneous vacuum matter condensation based on cosmic background density and field voids
[[nodiscard]] inline QuantumFluctuationEvent
evaluate_quantum_vacuum_condensation(float local_density_field, float rand_sample) noexcept {
    QuantumFluctuationEvent evt;
    // Lower local matter density increases spontaneous vacuum fluctuation probability (Dirac sea polarization)
    const float vacuum_potential = 1.0f / (1.0f + local_density_field * 0.05f);
    if (rand_sample < vacuum_potential * 0.85f) {
        evt.spawns_particle = true;
        evt.particle_mass = 30.0f + (1.0f - rand_sample) * 45.0f;
        evt.thermal_energy = 25.0f + rand_sample * 80.0f;
    }
    return evt;
}

// ── 12. Kilonova Explosions, r-Process Synthesis & Gamma-Ray Bursts (GRBs) ──────────────────

struct KilonovaResult {
    bool  triggers_kilonova = false;
    float grb_beam_energy = 0.0f;
    float gold_platinum_yield = 0.0f; // Heavy element enrichment delta_Z
    float remnant_mass = 0.0f;
    bool  forms_black_hole = false;
};

[[nodiscard]] inline KilonovaResult
evaluate_kilonova_merger(float m1, float m2, bool is_neutron_1, bool is_neutron_2,
                         bool is_bh_1, bool is_bh_2) noexcept {
    KilonovaResult res;
    // Binary Neutron Star (BNS) or Neutron Star-Black Hole (NSBH) coalescence
    if ((is_neutron_1 && is_neutron_2) || (is_neutron_1 && is_bh_2) || (is_neutron_2 && is_bh_1)) {
        res.triggers_kilonova = true;
        const float total_m = m1 + m2;
        res.remnant_mass = total_m * 0.88f; // ~12% mass converted to pure relativistic energy & ejecta
        res.gold_platinum_yield = std::clamp((m1 * m2) / 45000.0f, 0.02f, 0.08f);
        res.grb_beam_energy = total_m * 12.0f;
        res.forms_black_hole = (total_m > 950.0f); // Exceeds TOV maximum mass for neutron degeneracy
    }
    return res;
}

// ── 13. Planetary & Accretion Ring Formation Dynamics ───────────────────────────────────────

struct RingParticleSpec {
    pebble::math::vec2 pos{0.0f, 0.0f};
    pebble::math::vec2 vel{0.0f, 0.0f};
    float              radius = 0.6f;
    float              mass = 1.0f;
};

// Generates concentric Keplerian ring orbit particles for tidally disrupted moons
[[nodiscard]] inline RingParticleSpec
compute_ring_particle_keplerian(const pebble::math::vec2& host_pos, float host_mass,
                                float ring_radius, float angle, float particle_mass = 1.5f) noexcept {
    RingParticleSpec spec;
    const float cos_a = std::cos(angle);
    const float sin_a = std::sin(angle);
    spec.pos = host_pos + pebble::math::vec2{cos_a, sin_a} * ring_radius;
    
    // Circular Keplerian orbital speed: v = \sqrt{G * M / r}
    const float v_circ = std::sqrt(std::max(1.0f, (18000.0f * host_mass) / std::max(ring_radius, 1.0f)));
    // Tangential orbital velocity vector
    spec.vel = pebble::math::vec2{-sin_a, cos_a} * v_circ;
    spec.mass = particle_mass;
    spec.radius = 0.65f;
    return spec;
}

// ── 14. Gravitational Micro-Lensing Spacetime Deflection ───────────────────────────────────

[[nodiscard]] inline pebble::math::vec2
compute_einstein_micro_lensing(const pebble::math::vec2& ray_pos, const pebble::math::vec2& lens_pos,
                               float lens_mass, float min_impact = 4.0f) noexcept {
    const pebble::math::vec2 d = ray_pos - lens_pos;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);
    if (dist < 1.0f) return pebble::math::vec2{0.0f, 0.0f};

    // General Relativity Deflection Angle: \hat{\alpha} = \frac{4 G M}{c^2 b}
    const float impact_param = std::max(dist, min_impact);
    const float deflection_mag = (lens_mass * 1.8f) / (impact_param * impact_param + 64.0f);
    // Radial deflection towards the gravitating lens
    return pebble::math::vec2{-d[0] / dist, -d[1] / dist} * deflection_mag;
}

// ── 15. Cosmological Metric Expansion (Hubble Drift) ────────────────────────────────────────

[[nodiscard]] inline pebble::math::vec2
apply_hubble_metric_drift(const pebble::math::vec2& pos, const pebble::math::vec2& cosmic_center,
                          float hubble_constant, float dt) noexcept {
    // Hubble's Law: \vec{v}_H = H_0 \cdot \vec{r}
    const pebble::math::vec2 r = pos - cosmic_center;
    return r * (hubble_constant * dt);
}

// ── 16. Supermassive Black Hole (SMBH) Post-Newtonian Inspiral & Ringdown ─────────────────

struct SMBHInspiralState {
    bool  is_in_inspiral = false;
    float gw_chirp_frequency = 0.0f;
    float post_newtonian_drag = 0.0f;
    bool  triggers_ringdown_merger = false;
};

[[nodiscard]] inline SMBHInspiralState
evaluate_smbh_inspiral(float m1, float m2, float distance, float r_isco) noexcept {
    SMBHInspiralState state;
    if (distance < r_isco * 2.5f && distance > 0.5f) {
        state.is_in_inspiral = true;
        // Gravitational Wave Chirp Frequency: \omega \propto (M_chirp)^{5/8} * (r)^{-3/2}
        const float m_chirp = std::pow(m1 * m2, 0.6f) / std::pow(m1 + m2, 0.2f);
        state.gw_chirp_frequency = (std::sqrt(18000.0f * (m1 + m2)) / std::pow(distance, 1.5f)) * 4.0f;
        
        // Post-Newtonian (2.5PN) Radiation Reaction Drag Acceleration
        state.post_newtonian_drag = (m_chirp * 120.0f) / (distance * distance + 16.0f);
        state.triggers_ringdown_merger = (distance <= r_isco * 1.15f);
    }
    return state;
}

// ── 17. Stellar Spaghettification & Tidal Disruption Events (TDE) ───────────────────────────

struct TDESpaghettificationStream {
    bool  is_disrupting = false;
    float tidal_radius = 0.0f;
    float accretion_feed_rate = 0.0f;
};

[[nodiscard]] inline TDESpaghettificationStream
compute_tde_spaghettification(float star_mass, float star_radius, float bh_mass, float distance) noexcept {
    TDESpaghettificationStream stream;
    // Tidal Radius (Hills Radius): r_t = R_* * (M_BH / M_*)^(1/3)
    stream.tidal_radius = star_radius * std::cbrt(std::max(1.0f, bh_mass / std::max(star_mass, 1.0f)));
    if (distance < stream.tidal_radius && distance > 1.0f) {
        stream.is_disrupting = true;
        // Mass transfer rate feeding the ISCO accretion disk
        stream.accretion_feed_rate = std::clamp((stream.tidal_radius - distance) / stream.tidal_radius, 0.1f, 1.0f) * (star_mass * 0.45f);
    }
    return stream;
}

// ── 18. Morgan-Keenan (MK) Stellar Spectral Classification ──────────────────────────────────

enum class SpectralClassMK : std::uint8_t {
    ClassO, // Hyper-luminous Deep Blue Giant (> 30,000 K)
    ClassB, // Blue-White Giant (10,000 - 30,000 K)
    ClassA, // White Sirius (7,500 - 10,000 K)
    ClassF, // Yellow-White Procyon (6,000 - 7,500 K)
    ClassG, // Yellow Sol Sun-like (5,200 - 6,000 K)
    ClassK, // Orange Arcturus (3,700 - 5,200 K)
    ClassM  // Red Dwarf Proxima (< 3,700 K)
};

struct StellarSpectralInfo {
    SpectralClassMK cls = SpectralClassMK::ClassM;
    float r = 1.0f;
    float g = 1.0f;
    float b = 1.0f;
};

[[nodiscard]] inline StellarSpectralInfo
evaluate_stellar_spectral_class(float mass, float temp_celsius) noexcept {
    StellarSpectralInfo info;
    const float t_kelvin = temp_celsius + 273.15f;

    if (t_kelvin >= 28000.0f || mass > 900.0f) {
        info.cls = SpectralClassMK::ClassO;
        info.r = 0.45f; info.g = 0.65f; info.b = 1.0f; // Deep Blue
    } else if (t_kelvin >= 10000.0f || mass > 500.0f) {
        info.cls = SpectralClassMK::ClassB;
        info.r = 0.65f; info.g = 0.82f; info.b = 1.0f; // Blue-White
    } else if (t_kelvin >= 7500.0f || mass > 350.0f) {
        info.cls = SpectralClassMK::ClassA;
        info.r = 0.90f; info.g = 0.95f; info.b = 1.0f; // White
    } else if (t_kelvin >= 6000.0f || mass > 220.0f) {
        info.cls = SpectralClassMK::ClassF;
        info.r = 1.0f;  info.g = 0.98f; info.b = 0.85f; // Yellow-White
    } else if (t_kelvin >= 5200.0f || mass > 140.0f) {
        info.cls = SpectralClassMK::ClassG;
        info.r = 1.0f;  info.g = 0.88f; info.b = 0.35f; // Yellow Sun
    } else if (t_kelvin >= 3700.0f || mass > 80.0f) {
        info.cls = SpectralClassMK::ClassK;
        info.r = 1.0f;  info.g = 0.58f; info.b = 0.20f; // Orange Giant
    } else {
        info.cls = SpectralClassMK::ClassM;
        info.r = 1.0f;  info.g = 0.32f; info.b = 0.15f; // Red Dwarf
    }
    return info;
}



// ── 20. Stellar Wind & Coronal Mass Ejection (CME) Radiation Pressure ───────────────────────

struct StellarWindForce {
    pebble::math::vec2 force{0.0f, 0.0f};
    bool               triggers_cme = false;
};

[[nodiscard]] inline StellarWindForce
evaluate_stellar_wind_radiation_pressure(const pebble::math::vec2& star_pos, float star_mass,
                                         float star_temp, float star_radius,
                                         const pebble::math::vec2& target_pos, float rand_sample) noexcept {
    StellarWindForce res;
    if (star_temp < 1400.0f && star_mass < 120.0f) return res;

    const pebble::math::vec2 d = target_pos - star_pos;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);
    if (dist < star_radius || dist > 260.0f) return res;

    // Stefan-Boltzmann Luminosity: L \propto R^2 * T^4
    const float t_norm = star_temp / 5500.0f;
    const float luminosity = (star_radius * star_radius) * (t_norm * t_norm * t_norm * t_norm);
    
    // Radiation Pressure: F_rad = \frac{L}{4\pi r^2 c}
    const float rad_press = (luminosity * 140.0f) / (dist_sq + 100.0f);
    res.force = pebble::math::vec2{d[0] / dist, d[1] / dist} * rad_press;

    // Periodic Coronal Mass Ejection (CME) Magnetic Flare Eruptions
    if (star_temp > 2200.0f && rand_sample < 0.004f) {
        res.triggers_cme = true;
    }
    return res;
}

// ── 21. Barycentric Hierarchy Detection (Jacobi Coordinates) ───────────────────────────────

struct BarycentricPair {
    std::size_t        idx1 = 0;
    std::size_t        idx2 = 0;
    pebble::math::vec2 center_of_mass{0.0f, 0.0f};
    float              total_mass = 0.0f;
    float              separation = 0.0f;
    bool               is_bound = false;
};

[[nodiscard]] inline BarycentricPair
detect_binary_barycenter(std::size_t i, std::size_t j,
                         const pebble::math::vec2& p1, const pebble::math::vec2& v1, float m1,
                         const pebble::math::vec2& p2, const pebble::math::vec2& v2, float m2) noexcept {
    BarycentricPair pair;
    pair.idx1 = i;
    pair.idx2 = j;
    const pebble::math::vec2 d = p2 - p1;
    pair.separation = std::sqrt(d[0] * d[0] + d[1] * d[1]);
    pair.total_mass = m1 + m2;
    pair.center_of_mass = (p1 * m1 + p2 * m2) * (1.0f / pair.total_mass);

    // Mutual Orbital Specific Energy: \epsilon = \frac{1}{2} v_{rel}^2 - \frac{G M_{tot}}{r}
    const pebble::math::vec2 dv = v2 - v1;
    const float v_rel_sq = dv[0] * dv[0] + dv[1] * dv[1];
    const float spec_energy = 0.5f * v_rel_sq - (18000.0f * pair.total_mass) / (pair.separation + 10.0f);

    pair.is_bound = (spec_energy < 0.0f && pair.separation < 220.0f);
    return pair;
}

// ── 22. Cosmic Filament Web (Zel'dovich Approximation) ──────────────────────────────────────

struct CosmicFilamentBridge {
    pebble::math::vec2 node_a{0.0f, 0.0f};
    pebble::math::vec2 node_b{0.0f, 0.0f};
    float              filament_density = 0.0f;
};

[[nodiscard]] inline CosmicFilamentBridge
compute_cosmic_filament(const pebble::math::vec2& p1, float m1,
                        const pebble::math::vec2& p2, float m2, float max_span = 450.0f) noexcept {
    CosmicFilamentBridge f;
    f.node_a = p1;
    f.node_b = p2;
    const pebble::math::vec2 d = p2 - p1;
    const float len = std::sqrt(d[0] * d[0] + d[1] * d[1]);
    if (len > 30.0f && len < max_span) {
        // Gravitational bridge density between supermassive nodes
        f.filament_density = std::clamp((m1 * m2) / (len * len * 8.0f), 0.05f, 0.65f);
    }
    return f;
}

// ── 23. Spacetime Curvature & Geodesic Grid Embedding ──────────────────────────────────────

[[nodiscard]] inline pebble::math::vec2
compute_spacetime_geodesic_deflection(const pebble::math::vec2& grid_pt,
                                      const pebble::math::vec2& mass_pos,
                                      float mass, float softening = 24.0f) noexcept {
    const pebble::math::vec2 d = mass_pos - grid_pt;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);
    if (dist < 1.0f) return pebble::math::vec2{0.0f, 0.0f};

    // 2D Spacetime Curvature Warping: \Delta \vec{x} = \frac{G M}{r^2 + \epsilon^2} \hat{r}
    const float pinch_mag = (mass * 0.45f) / (dist_sq + softening * softening);
    return pebble::math::vec2{d[0] / dist, d[1] / dist} * std::min(pinch_mag, 16.0f);
}

// ── 24. Hawking Radiation Quantum Black Hole Evaporation ───────────────────────────────────

struct HawkingRadiationState {
    float mass_loss_rate = 0.0f;
    float hawking_temp = 0.0f;
    bool  triggers_gamma_flash = false;
};

[[nodiscard]] inline HawkingRadiationState
evaluate_hawking_radiation(float mass, float dt) noexcept {
    HawkingRadiationState res;
    if (mass < 1.0f) return res;

    // Hawking Temperature: T_H \propto 1 / M
    res.hawking_temp = 12000.0f / (mass * 0.05f + 1.0f);

    // Mass Loss Rate: dM/dt \propto -1 / M^2
    res.mass_loss_rate = (14.0f / (mass * mass * 0.001f + 1.0f)) * dt;

    // High-Energy Gamma-Ray Flash when below critical degenerate mass
    res.triggers_gamma_flash = (mass <= 45.0f);
    return res;
}

// ── 25. General Relativistic Gravitational Redshift ─────────────────────────────────────────

[[nodiscard]] inline float
compute_gravitational_redshift_factor(float mass, float radius, float distance) noexcept {
    // Gravitational Redshift Factor: z = \frac{1}{\sqrt{1 - \frac{2 G M}{c^2 r}}} - 1
    const float r_eff = std::max(radius, distance);
    const float rs = (mass * 0.0035f + 2.5f); // Effective Schwarzschild radius
    const float schw_ratio = std::clamp(rs / (r_eff + 1.0f), 0.0f, 0.88f);
    return (1.0f / std::sqrt(1.0f - schw_ratio)) - 1.0f;
}

// ── 26. Forward Keplerian / Osculating Orbit Prediction ──────────────────────────────────────

struct OrbitPredictionPoint {
    pebble::math::vec2 pos{0.0f, 0.0f};
    bool               is_bound = false;
};

[[nodiscard]] inline std::vector<pebble::math::vec2>
compute_osculating_orbit_points(const pebble::math::vec2& body_pos, const pebble::math::vec2& body_vel,
                                const pebble::math::vec2& host_pos, float host_mass,
                                int num_steps = 28, float dt_step = 0.08f) noexcept {
    std::vector<pebble::math::vec2> points;
    points.reserve(num_steps);

    pebble::math::vec2 sim_p = body_pos;
    pebble::math::vec2 sim_v = body_vel;

    for (int step = 0; step < num_steps; ++step) {
        const pebble::math::vec2 d = host_pos - sim_p;
        const float dist2 = d[0] * d[0] + d[1] * d[1] + 16.0f;
        const float dist = std::sqrt(dist2);
        const pebble::math::vec2 a = pebble::math::vec2{d[0] / dist, d[1] / dist} * ((18000.0f * host_mass) / dist2);

        sim_v = sim_v + a * dt_step;
        sim_p = sim_p + sim_v * dt_step;
        points.push_back(sim_p);
    }
    return points;
}

// ── 28. Cometary Outgassing & Sublimation Physics ────────────────────────────

struct CometSublimationResult {
    bool               is_sublimating = false;
    float              mass_loss_rate = 0.0f;
    pebble::math::vec2 tail_direction{0.0f, 0.0f}; // Anti-solar radiation direction
    float              tail_velocity_mag = 0.0f;
    bool               is_ion_plasma = false;       // Type I ion tail vs Type II dust tail
};

// Evaluates cometary ice sublimation and solar radiation pressure ion/dust tail ejection
[[nodiscard]] inline CometSublimationResult
evaluate_comet_tail_sublimation(const pebble::math::vec2& comet_pos, float comet_temp,
                                const pebble::math::vec2& star_pos, float star_temp,
                                float star_radius, float dt) noexcept {
    CometSublimationResult res;
    if (comet_temp < -40.0f) return res;

    const pebble::math::vec2 d = comet_pos - star_pos;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    const float dist = std::sqrt(dist_sq);
    if (dist < 1.0f || dist > 600.0f) return res;

    res.is_sublimating = true;
    res.tail_direction = pebble::math::vec2{d[0] / dist, d[1] / dist};

    // Sublimation rate \propto (T_comet - T_sublim) * (1 / r^2)
    const float solar_flux = (star_radius * star_radius * (star_temp + 273.15f)) / (dist_sq + 100.0f);
    res.mass_loss_rate = std::clamp(solar_flux * 0.005f * (comet_temp + 40.0f) * dt, 0.0001f, 0.5f);
    res.tail_velocity_mag = 40.0f + std::clamp(solar_flux * 12.0f, 10.0f, 180.0f);
    res.is_ion_plasma = (star_temp > 2500.0f || comet_temp > 150.0f);
    return res;
}

// ── 29. Open World Cosmic Boundary & Vacuum Recycling ─────────────────────────

struct OpenWorldCullResult {
    bool should_recycle = false;
    bool is_in_outer_rim = false;
};

// Evaluates if a body has escaped far beyond the active universe and can be recycled
[[nodiscard]] inline OpenWorldCullResult
evaluate_open_world_bounds(const pebble::math::vec2& pos, const pebble::math::vec2& center,
                           float active_radius = 2800.0f, float rim_radius = 1800.0f) noexcept {
    OpenWorldCullResult res;
    const pebble::math::vec2 d = pos - center;
    const float dist_sq = d[0] * d[0] + d[1] * d[1];
    if (dist_sq > active_radius * active_radius) {
        res.should_recycle = true;
    } else if (dist_sq > rim_radius * rim_radius) {
        res.is_in_outer_rim = true;
    }
    return res;
}

// ── 30. External Infall Celestial Entity Presets ──────────────────────────────

enum class InflowEntityType : std::uint8_t {
    RogueProtogalaxy,    // Rotating cluster of 8-24 stellar/planetary bodies
    HypervelocityStar,   // Fast-moving hot star traversing the cosmos
    RoguePulsarMagnetar, // Millisecond pulsar with energetic relativistic beams
    InterstellarComet    // High-eccentricity icy body with volatile inventory
};

struct InflowSpawnConfig {
    pebble::math::vec2 spawn_pos{0.0f, 0.0f};
    pebble::math::vec2 ingress_vel{0.0f, 0.0f};
    InflowEntityType   type = InflowEntityType::RogueProtogalaxy;
    float              core_mass = 250.0f;
    int                satellite_count = 6;
};

[[nodiscard]] inline InflowSpawnConfig
generate_random_inflow(float viewport_w, float viewport_h, float spawn_margin,
                       float rand_angle, float rand_speed_factor, InflowEntityType type) noexcept {
    InflowSpawnConfig cfg;
    cfg.type = type;
    const pebble::math::vec2 center{viewport_w * 0.5f, viewport_h * 0.5f};
    
    // Spawn around an ellipse beyond viewport perimeter
    const float rx = (viewport_w * 0.5f) + spawn_margin;
    const float ry = (viewport_h * 0.5f) + spawn_margin;
    cfg.spawn_pos = center + pebble::math::vec2{std::cos(rand_angle) * rx, std::sin(rand_angle) * ry};

    // Vector pointing generally towards center with natural orbital impact parameter deflection
    const pebble::math::vec2 to_center = center - cfg.spawn_pos;
    const float dist = std::sqrt(to_center[0] * to_center[0] + to_center[1] * to_center[1]);
    const pebble::math::vec2 dir = (dist > 1e-3f) ? (to_center * (1.0f / dist)) : pebble::math::vec2{1.0f, 0.0f};
    const pebble::math::vec2 tangent{-dir[1], dir[0]};

    // Deflect velocity to create parabolic / hyperbolic flybys rather than direct bullseye colliders
    const float deflection = (rand_speed_factor - 0.5f) * 0.65f;
    const pebble::math::vec2 v_dir = pebble::math::normalize(dir + tangent * deflection);

    switch (type) {
        case InflowEntityType::HypervelocityStar:
            cfg.ingress_vel = v_dir * (35.0f + rand_speed_factor * 30.0f);
            cfg.core_mass = 320.0f + rand_speed_factor * 280.0f;
            cfg.satellite_count = 0;
            break;
        case InflowEntityType::RoguePulsarMagnetar:
            cfg.ingress_vel = v_dir * (45.0f + rand_speed_factor * 40.0f);
            cfg.core_mass = 750.0f;
            cfg.satellite_count = 0;
            break;
        case InflowEntityType::InterstellarComet:
            cfg.ingress_vel = v_dir * (28.0f + rand_speed_factor * 25.0f);
            cfg.core_mass = 45.0f + rand_speed_factor * 35.0f;
            cfg.satellite_count = 3 + static_cast<int>(rand_speed_factor * 4.0f);
            break;
        case InflowEntityType::RogueProtogalaxy:
        default:
            cfg.ingress_vel = v_dir * (12.0f + rand_speed_factor * 18.0f);
            cfg.core_mass = 450.0f + rand_speed_factor * 400.0f;
            cfg.satellite_count = 8 + static_cast<int>(rand_speed_factor * 12.0f);
            break;
    }

    return cfg;
}

// ── 31. Roche Lobe Overflow (RLOF) & Accretion Stream Stripping ───────────────

struct RLOFTransferResult {
    bool  is_overflowing = false;
    float mass_transfer_rate = 0.0f; // Siphoned mass delta
    float roche_lobe_radius = 0.0f;  // Eggleton approximation
};

// Eggleton's analytical formula for Roche Lobe effective radius:
// R_lobe / a = \frac{0.49 q^{2/3}}{0.6 q^{2/3} + \ln(1 + q^{1/3})}
[[nodiscard]] inline RLOFTransferResult
evaluate_roche_lobe_overflow(float m_donor, float r_donor, float m_accretor, float distance, float dt) noexcept {
    RLOFTransferResult res;
    if (distance <= 1.0f || m_donor <= 0.0f || m_accretor <= 0.0f) return res;

    const float q = std::max(0.01f, m_donor / m_accretor); // Mass ratio
    const float q_13 = std::cbrt(q);
    const float q_23 = q_13 * q_13;
    const float r_lobe_ratio = (0.49f * q_23) / (0.6f * q_23 + std::log(1.0f + q_13));
    res.roche_lobe_radius = distance * r_lobe_ratio;

    if (r_donor > res.roche_lobe_radius) {
        res.is_overflowing = true;
        const float overflow_depth = (r_donor - res.roche_lobe_radius) / std::max(r_donor, 1.0f);
        // Hydrodynamic polytropic mass loss rate
        res.mass_transfer_rate = std::clamp(overflow_depth * m_donor * 0.04f * dt, 0.001f, m_donor * 0.15f);
    }
    return res;
}

// ── 32. Tidal Dissipation, Circularization & Spin-Orbit Locking ───────────────

struct TidalFrictionResult {
    float spin_torque = 0.0f;           // \tau_spin applied to body 1
    float orbital_damping_force = 0.0f; // Dissipative drag reducing orbital eccentricity
};

// Tidal torque: \tau = -\frac{3 k_2 G M_2^2 R_1^5}{Q d^6} (\omega_1 - \Omega_{orb})
[[nodiscard]] inline TidalFrictionResult
evaluate_tidal_locking_torque(float m1, float r1, float omega1,
                              float m2, float distance, float v_rel, float dt) noexcept {
    TidalFrictionResult res;
    if (distance <= 1.0f || m1 <= 0.0f || m2 <= 0.0f) return res;

    // Orbital angular frequency: \Omega_{orb} = v_tangent / d
    const float omega_orb = v_rel / std::max(distance, 1.0f);
    const float delta_omega = omega1 - omega_orb;

    // Love number k2 / Q tidal dissipation factor
    const float r1_5 = r1 * r1 * r1 * r1 * r1;
    const float d_6 = std::pow(distance, 6.0f);
    const float tidal_coeff = (18000.0f * (m2 * m2) * r1_5) / (d_6 + 1000.0f);

    // Apply torque towards tidal locking (delta_omega -> 0)
    res.spin_torque = -std::clamp(tidal_coeff * delta_omega * 0.015f * dt, -std::abs(delta_omega) * 0.5f, std::abs(delta_omega) * 0.5f);
    res.orbital_damping_force = std::clamp(tidal_coeff * 0.001f, 0.0f, 0.05f);
    return res;
}

// ── 33. Supernova Remnant (SNR) Sedov-Taylor Blast Wave ───────────────────────

struct SedovTaylorBlast {
    pebble::math::vec2 center{0.0f, 0.0f};
    float              radius = 2.0f;
    float              max_radius = 420.0f;
    float              energy = 1000.0f;
    float              age = 0.0f;
    float              max_age = 2.8f;
    float              density_compression = 4.0f; // Strong Rankine-Hugoniot shock jump condition
};

// Evaluates Sedov-Taylor self-similar blast wave expansion: R(t) = (E / \rho_0)^{1/5} t^{2/5}
[[nodiscard]] inline float
compute_sedov_taylor_radius(float energy, float ambient_density, float time_sec) noexcept {
    if (time_sec <= 0.0f) return 1.0f;
    const float scale = std::pow(std::max(10.0f, energy) / std::max(1.0f, ambient_density), 0.2f);
    return scale * std::pow(time_sec * 60.0f, 0.4f) * 18.0f;
}

// ── 34. Magnetohydrodynamic (MHD) Magnetic Flux Tubes ────────────────────────

struct MHDFluxTube {
    pebble::math::vec2 p1{0.0f, 0.0f};
    pebble::math::vec2 p2{0.0f, 0.0f};
    pebble::math::vec2 midpoint{0.0f, 0.0f};
    float              field_strength = 0.0f; // Tesla / Normalized magnetic potential
    float              current_intensity = 0.0f; // Birkeland current
};

// Evaluates dipolar magnetic connection and Birkeland currents between binary magnetic stars
[[nodiscard]] inline MHDFluxTube
compute_mhd_flux_tube(const pebble::math::vec2& p1, float m1, float omega1,
                      const pebble::math::vec2& p2, float m2, float omega2) noexcept {
    MHDFluxTube tube;
    tube.p1 = p1;
    tube.p2 = p2;
    const pebble::math::vec2 d = p2 - p1;
    const float dist = std::sqrt(d[0] * d[0] + d[1] * d[1]);
    if (dist < 1.0f || dist > 350.0f) return tube;

    // Midpoint bowed flux tube arc offset by mutual rotation
    const pebble::math::vec2 mid = (p1 + p2) * 0.5f;
    const pebble::math::vec2 normal{-d[1] / dist, d[0] / dist};
    const float bow = (omega1 + omega2) * 0.5f * (dist * 0.15f);
    tube.midpoint = mid + normal * bow;

    // Dipolar potential scaling B \propto (M_1 M_2 \omega_1 \omega_2) / d^3
    const float b_dipole = (m1 * m2 * std::abs(omega1 * omega2)) / (dist * dist * dist + 50.0f);
    tube.field_strength = std::clamp(b_dipole * 0.5f, 0.02f, 0.95f);
    tube.current_intensity = std::clamp(b_dipole * 0.25f, 0.01f, 0.65f);
    return tube;
}

// ── 35. Planetary Geology, Jeans Thermal Escape & Atmosphere Retention ───────

struct AtmosphericEscapeResult {
    bool  retains_atmosphere = false;
    float jeans_loss_rate = 0.0f;     // Mass loss rate due to thermal Jeans escape
    float wind_stripping_rate = 0.0f; // Mass loss due to stellar radiation pressure
    float escape_velocity = 0.0f;
    float thermal_velocity = 0.0f;
};

// Evaluates planetary atmosphere retention vs. Jeans thermal escape & stellar wind stripping:
// v_esc = \sqrt{2 G M / R},  v_th = \sqrt{3 k_B T / m_mol}
[[nodiscard]] inline AtmosphericEscapeResult
evaluate_jeans_atmospheric_escape(float planet_mass, float planet_radius, float planet_temp_celsius,
                                  float stellar_wind_flux, float dt) noexcept {
    AtmosphericEscapeResult res;
    if (planet_mass < 5.0f || planet_radius < 0.5f) return res;

    // Escape velocity: v_esc = \sqrt{2 * G * M / R}
    res.escape_velocity = std::sqrt((2.0f * 18000.0f * planet_mass) / planet_radius);

    // Thermal molecular speed: v_th \propto \sqrt{T_kelvin}
    const float t_kelvin = std::max(10.0f, planet_temp_celsius + 273.15f);
    res.thermal_velocity = std::sqrt(t_kelvin) * 14.5f;

    // Jeans parameter \lambda = (v_esc / v_th)^2
    const float lambda_jeans = (res.escape_velocity * res.escape_velocity) / (res.thermal_velocity * res.thermal_velocity + 1.0f);

    if (lambda_jeans >= 6.0f) {
        // High retention: strong gravity holds volatile atmosphere
        res.retains_atmosphere = true;
        // Residual thermal tail escape
        res.jeans_loss_rate = std::clamp(std::exp(-lambda_jeans) * planet_mass * 0.005f * dt, 0.0f, 0.05f);
    } else {
        // Active Jeans blowout escape
        res.retains_atmosphere = false;
        res.jeans_loss_rate = std::clamp((6.0f - lambda_jeans) * 0.02f * planet_mass * dt, 0.001f, planet_mass * 0.2f);
    }

    // Unshielded stellar wind stripping
    res.wind_stripping_rate = std::clamp(stellar_wind_flux * 0.008f * dt, 0.0f, 0.1f);
    return res;
}

// ── 36. Surface Hydrology, Ocean Condensation & Continental Solidification ──

struct PlanetarySurfaceState {
    float ocean_coverage = 0.0f;     // 0.0 to 1.0 (Liquid surface water)
    float crust_solidification = 0.0f;// 0.0 (molten magma) to 1.0 (solid lithosphere)
    bool  in_habitable_zone = false;  // Temperature in 0 - 100 C range
};

// Evaluates surface liquid ocean condensation and tectonic plate cooling
[[nodiscard]] inline PlanetarySurfaceState
evaluate_surface_hydrology_phase(float temperature_celsius, float volatile_water_fraction,
                                 float planet_mass) noexcept {
    PlanetarySurfaceState state;
    if (planet_mass < 15.0f || planet_mass > 400.0f) return state;

    // Habitable thermal window for liquid water
    state.in_habitable_zone = (temperature_celsius >= -5.0f && temperature_celsius <= 95.0f);

    // Crust solidification: 1000 C -> 0 C transition
    state.crust_solidification = std::clamp((1000.0f - temperature_celsius) / 900.0f, 0.0f, 1.0f);

    // Surface ocean condensation: requires cool solid crust and water volatile inventory
    if (state.in_habitable_zone && state.crust_solidification > 0.6f) {
        state.ocean_coverage = std::clamp(volatile_water_fraction * 1.8f * state.crust_solidification, 0.0f, 0.85f);
    }
    return state;
}

// ── 37. Quark-Gluon Plasma (QGP) / Strange Quark Star Transition ──────────────

struct StrangeStarTransition {
    bool  triggers_strange_star = false;
    float deconfined_energy_release = 0.0f;
    float strange_radius = 2.6f;
};

// Evaluates transition into Strange Quark Star (Witten Strange Matter Hypothesis)
[[nodiscard]] inline StrangeStarTransition
evaluate_strange_star_transition(float mass, bool is_neutron_star, float core_pressure) noexcept {
    StrangeStarTransition res;
    // Massive neutron star collapse beyond Chandrasekhar / near TOV limit (M \in [820, 940])
    if (is_neutron_star && mass >= 820.0f && mass < 950.0f && core_pressure > 180.0f) {
        res.triggers_strange_star = true;
        res.deconfined_energy_release = mass * 18.0f;
        res.strange_radius = std::clamp(2.6f * (820.0f / mass), 1.8f, 2.8f);
    }
    return res;
}

// ── 38. Pulsar Timing Array (PTA) Gravitational Wave Modulation ───────────────

struct PTATimingResidual {
    float timing_shift_ns = 0.0f; // Nanosecond pulse arrival time residual
    float modulated_spin = 0.0f;
};

// Evaluates spin beacon pulse modulation from quadrupole gravitational wave strain
[[nodiscard]] inline PTATimingResidual
evaluate_pulsar_gw_timing_residual(float base_omega, float gw_strain, float gw_chirp_freq, float time_sec) noexcept {
    PTATimingResidual res;
    // Fractional frequency perturbation: \delta \nu / \nu = -0.5 * h_ij(t)
    const float gw_phase = std::sin(gw_chirp_freq * 6.2831853f * time_sec);
    const float frac_perturbation = -0.5f * gw_strain * gw_phase;
    res.modulated_spin = base_omega * (1.0f + frac_perturbation);
    res.timing_shift_ns = gw_strain * 140.0f * gw_phase;
    return res;
}

} // namespace prakriti::celestial


